### ISSUE TITLE
Hability to have only one background image url

### ISSUE THREAD

**Issue by Karbust** [twolfson/spritesmith#85]
### Result (there's a total of 3429 icons): 

```css
.icon-00010 {
  background-image: url(../images/icons-sprite-official.webp);
  background-position: -34px -288px;
  width: 32px;
  height: 64px;
}
```

Originates this error when not using CSSO:

```
./src/css/icons-sprite-official.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/css/icons-sprite-official.css)
Module parse failed: Maximum call stack size exceeded
File was processed with these loaders:
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/src/index.js
You may need an additional loader to handle the result of these loaders.
RangeError: Maximum call stack size exceeded
```

When using CSSO the minified CSS file still has a lot of background image url, but not enough to trigger the error.

### Expected

Something like this:

```css
.icon {
	background-image: url(imagens/icon-sprite.png?20210410224131);
	background-repeat: no-repeat;
	background-size: 2080px 2048px;
	display: inline-block;
}
.icon-00010 { background-position: -320px -320px; width: 32px; height: 64px; }
```

### Environment
I'm using React, with Create React App.
